# Render Blueprint for Backend Deployment
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: crm-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/auth/check
